import React, { useState } from "react";

/*
=========================================================
AI WEBSITE BUILDER
=========================================================

Architecture:

User Prompt
    ↓
Gemini AI
    ↓
CMS-compatible website JSON
    ↓
AI Preview

The preview reads the EXISTING CMS section structure:

navigation
hero
about
services
portfolio
contact
footer

No HTML/JSX/CSS is generated by Gemini.
=========================================================
*/


/* =========================================================
   HELPERS
========================================================= */

/*
  Gemini may return either:
  - normal strings
  - Portable Text arrays

  This helper allows the preview to safely display both.
*/
const getText = (value) => {
  if (value === null || value === undefined) {
    return "";
  }

  if (typeof value === "string") {
    return value;
  }

  if (typeof value === "number") {
    return String(value);
  }

  if (Array.isArray(value)) {
    return value
      .map((block) => {
        if (typeof block === "string") {
          return block;
        }

        if (block?.children && Array.isArray(block.children)) {
          return block.children
            .map((child) => child?.text || "")
            .join("");
        }

        return "";
      })
      .join("\n");
  }

  return "";
};


/*
  Safely extract a URL.
*/
const getUrl = (value) => {
  if (!value) {
    return "";
  }

  if (typeof value === "string") {
    return value;
  }

  return "";
};


/*
  Convert markdown-style links generated by AI into
  normal readable text for the preview.
*/
const cleanText = (value) => {
  const text = getText(value);

  return text
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1")
    .replace(/\\n/g, "\n")
    .trim();
};


/*
  Safely create a color.
*/
const safeColor = (value, fallback) => {
  if (!value || typeof value !== "string") {
    return fallback;
  }

  return value;
};


/*
  Safely create an image URL.
*/
const safeImage = (value) => {
  if (!value || typeof value !== "string") {
    return "";
  }

  return value;
};


/* =========================================================
   MAIN COMPONENT
========================================================= */

export default function AIWebsiteBuilder() {
  const [prompt, setPrompt] = useState("");
  const [website, setWebsite] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");


  /* =======================================================
     EXAMPLE PROMPTS
  ======================================================= */

  const examplePrompts = [
    "Create a premium portfolio website for a software developer with a dark theme, hero, skills, projects and contact sections.",

    "Create a modern restaurant website with a beautiful hero section, menu, gallery, testimonials, location and contact section.",

    "Create a pink Pinterest-style portfolio for a UI/UX designer with about, skills, projects, experience and contact sections.",
  ];


  /* =======================================================
     GENERATE WEBSITE
  ======================================================= */

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      setError(
        "Please describe the website you want to create."
      );

      return;
    }

    setLoading(true);
    setError("");
    setWebsite(null);

    try {
      console.log(
        "===================================="
      );

      console.log(
        "SENDING PROMPT TO AI:"
      );

      console.log(prompt);

      console.log(
        "===================================="
      );


      const response = await fetch(
        "http://localhost:5000/api/ai/generate",
        {
          method: "POST",

          headers: {
            "Content-Type": "application/json",
          },

          body: JSON.stringify({
            prompt: prompt.trim(),
          }),
        }
      );


      const data = await response.json();


      console.log(
        "===================================="
      );

      console.log(
        "AI RESPONSE:"
      );

      console.log(data);

      console.log(
        "===================================="
      );


      if (!response.ok) {
        throw new Error(
          data?.error ||
            "AI generation failed"
        );
      }


      if (!data.success) {
        throw new Error(
          data?.error ||
            "Something went wrong"
        );
      }


      if (!data.website) {
        throw new Error(
          "Gemini returned an empty website configuration."
        );
      }


      /*
        IMPORTANT:

        Gemini returns:

        {
          navigation,
          hero,
          about,
          services,
          portfolio,
          contact,
          footer
        }

        Store that complete object.
      */

      console.log(
        "GENERATED CMS WEBSITE:"
      );

      console.log(
        JSON.stringify(
          data.website,
          null,
          2
        )
      );


      setWebsite(data.website);

    } catch (err) {
      console.error(
        "AI CONNECTION ERROR:",
        err
      );

      setError(
        err?.message ||
          "Could not connect to the AI backend. Make sure your AI backend is running on port 5000."
      );

    } finally {
      setLoading(false);
    }
  };


  /* =======================================================
     EXAMPLE CLICK
  ======================================================= */

  const handleExampleClick = (
    example
  ) => {
    setPrompt(example);
    setError("");
    setWebsite(null);
  };


  /* =======================================================
     CLEAR
  ======================================================= */

  const handleClear = () => {
    setPrompt("");
    setWebsite(null);
    setError("");
  };


  /* =======================================================
     RENDER
  ======================================================= */

  return (
    <div style={styles.page}>

      <div style={styles.container}>

        {/* =================================================
            HEADER
        ================================================= */}

        <div style={styles.header}>

          <div style={styles.icon}>
            ✨
          </div>

          <div>
            <h1 style={styles.title}>
              AI Website Builder
            </h1>

            <p style={styles.subtitle}>
              Describe your website and let AI
              transform your idea into your
              existing CMS structure.
            </p>
          </div>

        </div>


        {/* =================================================
            PROMPT CARD
        ================================================= */}

        <div style={styles.card}>

          <label style={styles.label}>
            What website do you want to create?
          </label>


          <textarea
            value={prompt}
            onChange={(e) => {
              setPrompt(e.target.value);
              setError("");
            }}
            placeholder="Example: Create a premium portfolio website for a software developer with a dark theme, hero section, skills, projects and contact section..."
            style={styles.textarea}
            disabled={loading}
          />


          {/* CHARACTER COUNT */}

          <div style={styles.bottomRow}>

            <span style={styles.characterCount}>
              {prompt.length} characters
            </span>


            {prompt && (
              <button
                onClick={handleClear}
                style={styles.clearButton}
                disabled={loading}
              >
                Clear
              </button>
            )}

          </div>


          {/* ERROR */}

          {error && (
            <div style={styles.error}>

              <span>
                ⚠️
              </span>

              <span>
                {error}
              </span>

            </div>
          )}


          {/* GENERATE */}

          <button
            onClick={handleGenerate}
            disabled={loading}
            style={{
              ...styles.generateButton,

              opacity: loading
                ? 0.7
                : 1,

              cursor: loading
                ? "not-allowed"
                : "pointer",
            }}
          >

            {loading ? (
              <>
                <span
                  style={styles.spinner}
                >
                  ⏳
                </span>

                Generating...
              </>
            ) : (
              <>
                ✨ Generate Website
              </>
            )}

          </button>

        </div>


        {/* =================================================
            EXAMPLES
        ================================================= */}

        <div style={styles.examplesSection}>

          <h2 style={styles.sectionTitle}>
            💡 Try an example
          </h2>


          <div style={styles.examplesGrid}>

            {examplePrompts.map(
              (example, index) => (
                <button
                  key={index}
                  onClick={() =>
                    handleExampleClick(
                      example
                    )
                  }
                  style={styles.exampleCard}
                  disabled={loading}
                >

                  <div
                    style={
                      styles.exampleNumber
                    }
                  >
                    {index + 1}
                  </div>


                  <div
                    style={
                      styles.exampleText
                    }
                  >
                    {example}
                  </div>

                </button>
              )
            )}

          </div>

        </div>


        {/* =================================================
            PREVIEW
        ================================================= */}

        {website && (

          <div style={styles.previewCard}>

            {/* PREVIEW HEADER */}

            <div
              style={
                styles.previewHeader
              }
            >

              <div>

                <h2
                  style={
                    styles.previewTitle
                  }
                >
                  🌐 Live Website Preview
                </h2>


                <p
                  style={
                    styles.previewSubtitle
                  }
                >
                  Your website was generated
                  by Gemini using the existing
                  CMS structure.
                </p>

              </div>


              <div
                style={
                  styles.successBadge
                }
              >
                ✓ Generated
              </div>

            </div>


            {/* =================================================
                WEBSITE
            ================================================= */}

            <div
              style={{
                ...styles.preview,

                background:
                  safeColor(
                    website?.hero
                      ?.backgroundColor,
                    "#ffffff"
                  ),

                color:
                  safeColor(
                    website?.hero
                      ?.textColor,
                    "#222222"
                  ),
              }}
            >

              {/* =================================================
                  NAVIGATION
              ================================================= */}

              <PreviewNavigation
                navigation={
                  website.navigation
                }
              />


              {/* =================================================
                  HERO
              ================================================= */}

              <PreviewHero
                hero={
                  website.hero
                }
              />


              {/* =================================================
                  ABOUT
              ================================================= */}

              <PreviewAbout
                about={
                  website.about
                }
              />


              {/* =================================================
                  SERVICES
              ================================================= */}

              <PreviewServices
                services={
                  website.services
                }
              />


              {/* =================================================
                  PORTFOLIO
              ================================================= */}

              <PreviewPortfolio
                portfolio={
                  website.portfolio
                }
              />


              {/* =================================================
                  CONTACT
              ================================================= */}

              <PreviewContact
                contact={
                  website.contact
                }
              />


              {/* =================================================
                  FOOTER
              ================================================= */}

              <PreviewFooter
                footer={
                  website.footer
                }
              />

            </div>

          </div>
        )}

      </div>

    </div>
  );
}


/* =========================================================
   NAVIGATION PREVIEW
========================================================= */

function PreviewNavigation({
  navigation,
}) {
  if (!navigation) {
    return null;
  }


  const menuItems =
    Array.isArray(
      navigation.menuItems
    )
      ? navigation.menuItems.filter(
          (item) =>
            item?.show !== false
        )
      : [];


  return (
    <nav
      style={{
        ...styles.cmsNavbar,

        background:
          safeColor(
            navigation.backgroundColor,
            "#111827"
          ),

        color:
          safeColor(
            navigation.textColor,
            "#ffffff"
          ),
      }}
    >

      {/* SITE TITLE */}

      <div
        style={
          styles.cmsSiteTitle
        }
      >
        {cleanText(
          navigation.siteTitle
        ) || "My Website"}
      </div>


      {/* MENU */}

      <div
        style={
          styles.cmsNavLinks
        }
      >

        {menuItems.map(
          (item, index) => (

            <a
              key={
                item?._key ||
                index
              }
              href={
                item?.link ||
                "#"
              }
              style={{
                ...styles.cmsNavLink,

                color:
                  safeColor(
                    navigation.textColor,
                    "#ffffff"
                  ),
              }}
              onClick={(e) => {
                const link =
                  item?.link || "";

                if (
                  link.startsWith("#")
                ) {
                  e.preventDefault();

                  const target =
                    document.querySelector(
                      link
                    );

                  if (target) {
                    target.scrollIntoView({
                      behavior:
                        "smooth",
                    });
                  }
                }
              }}
            >
              {cleanText(
                item?.label
              )}
            </a>

          )
        )}

      </div>

    </nav>
  );
}


/* =========================================================
   HERO PREVIEW
========================================================= */

function PreviewHero({
  hero,
}) {
  if (!hero) {
    return null;
  }


  if (
    hero.showSection === false
  ) {
    return null;
  }


  const image =
    safeImage(
      hero.imageUrl ||
      hero.heroImage
    );


  const buttons =
    Array.isArray(
      hero.buttons
    )
      ? hero.buttons
      : [];


  const backgroundColor =
    safeColor(
      hero.backgroundColor,
      "#111827"
    );


  const textColor =
    safeColor(
      hero.textColor,
      "#ffffff"
    );


  return (
    <section
      id="home"
      style={{
        ...styles.cmsHero,

        backgroundColor:
          backgroundColor,

        color:
          textColor,

        backgroundImage:
          hero.useBackgroundImage &&
          hero.heroBackground
            ? `url(${hero.heroBackground})`
            : "none",

        backgroundSize:
          hero.backgroundSize ||
          "cover",

        backgroundPosition:
          hero.backgroundPosition ||
          "center",
      }}
    >

      {/* OVERLAY */}

      {hero.showOverlay &&
        hero.heroBackground && (
          <div
            style={{
              ...styles.heroOverlay,

              background:
                hero.overlayColor ||
                "rgba(0,0,0,0.35)",
            }}
          />
        )}


      <div
        style={{
          ...styles.heroContent,

          textAlign:
            hero.textAlign ||
            "center",

          position: "relative",

          zIndex: 2,
        }}
      >

        {/* IMAGE */}

        {image && (
          <img
            src={image}
            alt=""
            style={{
              ...styles.heroImage,

              borderRadius:
                hero.imageShape ===
                "circle"
                  ? "50%"
                  : hero.imageShape ===
                    "diamond"
                  ? "25%"
                  : "18px",

              width: "150px",
              height: "150px",
              objectFit: "cover",

              transform:
                hero.imageShape ===
                "diamond"
                  ? "rotate(45deg)"
                  : "none",
            }}
          />
        )}


        {/* NAME */}

        <h1
          style={
            styles.cmsHeroHeading
          }
        >
          {cleanText(
            hero.name ||
            hero.heading ||
            "Welcome"
          )}
        </h1>


        {/* ROLE */}

        <h2
          style={
            styles.cmsHeroRole
          }
        >
          {cleanText(
            hero.role ||
            hero.subheading
          )}
        </h2>


        {/* TAGLINE */}

        <p
          style={
            styles.cmsHeroDescription
          }
        >
          {cleanText(
            hero.tagline ||
            hero.description
          )}
        </p>


        {/* BUTTONS */}

        {buttons.length > 0 && (

          <div
            style={
              styles.heroButtons
            }
          >

            {buttons.map(
              (button, index) => (

                <a
                  key={
                    button?._key ||
                    index
                  }
                  href={
                    button?.url ||
                    "#"
                  }
                  target={
                    button?.openInNewTab
                      ? "_blank"
                      : undefined
                  }
                  rel={
                    button?.openInNewTab
                      ? "noreferrer"
                      : undefined
                  }
                  style={{
                    ...styles.cmsButton,

                    background:
                      button?.variant ===
                      "outline"
                        ? "transparent"
                        : button
                            ?.backgroundColor ||
                          "#ffffff",

                    color:
                      button
                        ?.textColor ||
                      backgroundColor,

                    border:
                      button?.variant ===
                      "outline"
                        ? `2px solid ${
                            button?.borderColor ||
                            textColor
                          }`
                        : "none",
                  }}
                >
                  {cleanText(
                    button?.label ||
                    button?.text
                  )}
                </a>

              )
            )}

          </div>
        )}

      </div>

    </section>
  );
}


/* =========================================================
   ABOUT PREVIEW
========================================================= */

function PreviewAbout({
  about,
}) {
  if (!about) {
    return null;
  }


  if (
    about.showSection === false
  ) {
    return null;
  }


  const features =
    Array.isArray(
      about.features
    )
      ? about.features
      : [];


  const image =
    safeImage(
      about.profileImageUrl ||
      about.profileImage
    );


  return (
    <section
      id="about"
      style={{
        ...styles.cmsSection,

        background:
          safeColor(
            about.backgroundColor,
            "#ffffff"
          ),

        color: "#222222",

        textAlign:
          about.textAlign ||
          "left",
      }}
    >

      <div
        style={
          styles.sectionInner
        }
      >

        {/* IMAGE */}

        {image && (
          <img
            src={image}
            alt=""
            style={{
              ...styles.aboutImage,

              borderRadius:
                about.imageShape ===
                "circle"
                  ? "50%"
                  : "18px",
            }}
          />
        )}


        <div
          style={
            styles.sectionText
          }
        >

          <h2
            style={
              styles.cmsSectionHeading
            }
          >
            {cleanText(
              about.heading
            ) || "About"}
          </h2>


          <p
            style={
              styles.cmsSectionDescription
            }
          >
            {cleanText(
              about.description
            )}
          </p>


          {/* FEATURES */}

          {features.length > 0 && (

            <div
              style={
                styles.featureGrid
              }
            >

              {features.map(
                (feature, index) => (

                  <div
                    key={
                      feature?._key ||
                      index
                    }
                    style={{
                      ...styles.featureCard,

                      background:
                        feature?.background ||
                        "#f8fafc",

                      borderRadius:
                        feature?.borderRadius ||
                        "14px",

                      boxShadow:
                        feature?.boxShadow
                          ? "0 5px 20px rgba(0,0,0,0.08)"
                          : "none",
                    }}
                  >

                    <h3>
                      {cleanText(
                        feature?.title
                      )}
                    </h3>

                    <p>
                      {cleanText(
                        feature?.description
                      )}
                    </p>

                  </div>

                )
              )}

            </div>
          )}

        </div>

      </div>

    </section>
  );
}


/* =========================================================
   SERVICES PREVIEW
========================================================= */

function PreviewServices({
  services,
}) {
  if (!services) {
    return null;
  }


  if (
    services.showSection === false
  ) {
    return null;
  }


  const list =
    Array.isArray(
      services.servicesList
    )
      ? services.servicesList
      : [];


  return (
    <section
      id="services"
      style={{
        ...styles.cmsSection,

        background:
          safeColor(
            services.backgroundColor,
            "#f8fafc"
          ),
      }}
    >

      <div
        style={
          styles.sectionInner
        }
      >

        <h2
          style={
            styles.cmsSectionHeading
          }
        >
          {cleanText(
            services.heading
          ) || "Services"}
        </h2>


        <p
          style={
            styles.cmsSectionDescription
          }
        >
          {cleanText(
            services.description
          )}
        </p>


        <div
          style={{
            ...styles.serviceGrid,

            gridTemplateColumns:
              services.layout ===
              "single"
                ? "1fr"
                : services.layout ===
                  "twoColumn"
                ? "repeat(2, minmax(0, 1fr))"
                : "repeat(3, minmax(0, 1fr))",
          }}
        >

          {list.map(
            (service, index) => {

              const image =
                safeImage(
                  service?.serviceImage
                );


              return (
                <div
                  key={
                    service?._key ||
                    index
                  }
                  style={{
                    ...styles.serviceCard,

                    background:
                      service
                        ?.cardBackground ||
                      "#ffffff",

                    borderRadius:
                      service
                        ?.cardBorderRadius ||
                      "16px",

                    boxShadow:
                      service
                        ?.cardShadow
                        ? "0 8px 25px rgba(0,0,0,0.08)"
                        : "0 2px 10px rgba(0,0,0,0.04)",
                  }}
                >

                  {image &&
                    service?.showImage !==
                      false && (
                      <img
                        src={image}
                        alt=""
                        style={
                          styles.serviceImage
                        }
                      />
                    )}


                  <h3>
                    {cleanText(
                      service
                        ?.serviceTitle
                    )}
                  </h3>


                  <p>
                    {cleanText(
                      service
                        ?.serviceDescription
                    )}
                  </p>


                  {service
                    ?.showButton && (
                    <a
                      href={
                        service
                          ?.buttonLink ||
                        "#"
                      }
                      style={{
                        ...styles.smallButton,

                        background:
                          service
                            ?.buttonColor ||
                          "#111827",
                      }}
                    >
                      {cleanText(
                        service
                          ?.buttonText
                      ) || "Learn More"}
                    </a>
                  )}

                </div>
              );
            }
          )}

        </div>

      </div>

    </section>
  );
}


/* =========================================================
   PORTFOLIO PREVIEW
========================================================= */

function PreviewPortfolio({
  portfolio,
}) {
  if (!portfolio) {
    return null;
  }


  if (
    portfolio.showSection === false
  ) {
    return null;
  }


  const projects =
    Array.isArray(
      portfolio.projects
    )
      ? portfolio.projects.filter(
          (project) =>
            project?.showProject !==
            false
        )
      : [];


  return (
    <section
      id="portfolio"
      style={{
        ...styles.cmsSection,

        background:
          safeColor(
            portfolio.backgroundColor,
            "#ffffff"
          ),
      }}
    >

      <div
        style={
          styles.sectionInner
        }
      >

        <h2
          style={
            styles.cmsSectionHeading
          }
        >
          {cleanText(
            portfolio.heading
          ) || "Portfolio"}
        </h2>


        <p
          style={
            styles.cmsSectionDescription
          }
        >
          {cleanText(
            portfolio.description
          )}
        </p>


        <div
          style={{
            ...styles.projectGrid,

            gridTemplateColumns:
              portfolio.gridLayout ===
              "one"
                ? "1fr"
                : portfolio.gridLayout ===
                  "two"
                ? "repeat(2, minmax(0, 1fr))"
                : "repeat(3, minmax(0, 1fr))",
          }}
        >

          {projects.map(
            (project, index) => {

              const image =
                safeImage(
                  project?.imageUrl
                );


              return (
                <div
                  key={
                    project?._key ||
                    index
                  }
                  style={
                    styles.projectCard
                  }
                >

                  {image &&
                    project?.showImage !==
                      false && (
                      <img
                        src={image}
                        alt=""
                        style={
                          styles.projectImage
                        }
                      />
                    )}


                  <h3>
                    {cleanText(
                      project?.title
                    )}
                  </h3>


                  <p>
                    {cleanText(
                      project
                        ?.description
                    )}
                  </p>


                  {project?.category && (
                    <span
                      style={
                        styles.projectBadge
                      }
                    >
                      {cleanText(
                        project.category
                      )}
                    </span>
                  )}


                  {project?.client && (
                    <div
                      style={
                        styles.projectMeta
                      }
                    >
                      Client:{" "}
                      {cleanText(
                        project.client
                      )}
                    </div>
                  )}


                  {project
                    ?.completionDate && (
                    <div
                      style={
                        styles.projectMeta
                      }
                    >
                      {cleanText(
                        project
                          .completionDate
                      )}
                    </div>
                  )}


                  {project
                    ?.showButton && (
                    <a
                      href={
                        project
                          ?.buttonLink ||
                        "#"
                      }
                      style={
                        styles.smallButton
                      }
                    >
                      {cleanText(
                        project
                          ?.buttonText
                      ) || "View Project"}
                    </a>
                  )}

                </div>
              );
            }
          )}

        </div>

      </div>

    </section>
  );
}


/* =========================================================
   CONTACT PREVIEW
========================================================= */

function PreviewContact({
  contact,
}) {
  if (!contact) {
    return null;
  }


  if (
    contact.showSection === false
  ) {
    return null;
  }


  const items =
    Array.isArray(
      contact.contactItems
    )
      ? contact.contactItems
      : [];


  return (
    <section
      id="contact"
      style={{
        ...styles.cmsSection,

        background:
          safeColor(
            contact.backgroundColor,
            "#f8fafc"
          ),

        textAlign:
          contact.textAlign ||
          "left",
      }}
    >

      <div
        style={
          styles.sectionInner
        }
      >

        <h2
          style={{
            ...styles.cmsSectionHeading,

            color:
              contact.headingColor ||
              "#111827",
          }}
        >
          {cleanText(
            contact.heading
          ) || "Contact"}
        </h2>


        <p
          style={{
            ...styles.cmsSectionDescription,

            color:
              contact.descriptionColor ||
              "#555555",
          }}
        >
          {cleanText(
            contact.description
          )}
        </p>


        {items.length > 0 && (

          <div
            style={
              styles.contactGrid
            }
          >

            {items.map(
              (item, index) => (

                <div
                  key={
                    item?._key ||
                    index
                  }
                  style={{
                    ...styles.contactItem,

                    background:
                      contact.cardBackground ||
                      "#ffffff",

                    boxShadow:
                      contact.cardShadow
                        ? "0 6px 20px rgba(0,0,0,0.08)"
                        : "none",
                  }}
                >

                  <strong
                    style={{
                      color:
                        contact.labelColor ||
                        "#111827",
                    }}
                  >
                    {cleanText(
                      item?.label
                    )}
                  </strong>


                  {item?.link ? (
                    <a
                      href={
                        item.link
                      }
                      target={
                        item
                          ?.openInNewTab
                          ? "_blank"
                          : undefined
                      }
                      rel={
                        item
                          ?.openInNewTab
                          ? "noreferrer"
                          : undefined
                      }
                      style={{
                        color:
                          contact.valueColor ||
                          "#555555",
                      }}
                    >
                      {cleanText(
                        item?.value
                      )}
                    </a>
                  ) : (
                    <span
                      style={{
                        color:
                          contact.valueColor ||
                          "#555555",
                      }}
                    >
                      {cleanText(
                        item?.value
                      )}
                    </span>
                  )}

                </div>

              )
            )}

          </div>
        )}

      </div>

    </section>
  );
}


/* =========================================================
   FOOTER PREVIEW
========================================================= */

function PreviewFooter({
  footer,
}) {
  if (!footer) {
    return null;
  }


  if (
    footer.showFooter === false
  ) {
    return null;
  }


  const quickLinks =
    Array.isArray(
      footer.quickLinks
    )
      ? footer.quickLinks
      : [];


  const contactItems =
    Array.isArray(
      footer.contactItems
    )
      ? footer.contactItems
      : [];


  const socialLinks =
    Array.isArray(
      footer.socialLinks
    )
      ? footer.socialLinks
      : [];


  return (
    <footer
      style={{
        ...styles.cmsFooter,

        background:
          safeColor(
            footer.backgroundColor,
            "#111827"
          ),

        color:
          safeColor(
            footer.textColor,
            "#ffffff"
          ),
      }}
    >

      <div
        style={
          styles.footerGrid
        }
      >

        {/* COMPANY */}

        <div>

          <h3
            style={{
              color:
                footer.headingColor ||
                "#ffffff",
            }}
          >
            {cleanText(
              footer.companyName
            ) || "Company"}
          </h3>


          <p>
            {cleanText(
              footer.companyDescription
            )}
          </p>

        </div>


        {/* QUICK LINKS */}

        {quickLinks.length > 0 && (

          <div>

            <h3
              style={{
                color:
                  footer.headingColor ||
                  "#ffffff",
              }}
            >
              Quick Links
            </h3>


            <div
              style={
                styles.footerLinks
              }
            >

              {quickLinks.map(
                (link, index) => (

                  <a
                    key={
                      link?._key ||
                      index
                    }
                    href={
                      link?.link ||
                      "#"
                    }
                    target={
                      link
                        ?.openInNewTab
                        ? "_blank"
                        : undefined
                    }
                    rel={
                      link
                        ?.openInNewTab
                        ? "noreferrer"
                        : undefined
                    }
                    style={{
                      color:
                        footer.linkColor ||
                        "#ffffff",
                    }}
                  >
                    {cleanText(
                      link?.title
                    )}
                  </a>

                )
              )}

            </div>

          </div>

        )}


        {/* CONTACT */}

        {contactItems.length > 0 && (

          <div>

            <h3
              style={{
                color:
                  footer.headingColor ||
                  "#ffffff",
              }}
            >
              Contact
            </h3>


            {contactItems.map(
              (item, index) => (

                <div
                  key={
                    item?._key ||
                    index
                  }
                  style={
                    styles.footerContact
                  }
                >

                  <strong>
                    {cleanText(
                      item?.label
                    )}
                  </strong>

                  <div>
                    {cleanText(
                      item?.value
                    )}
                  </div>

                </div>

              )
            )}

          </div>

        )}


        {/* SOCIAL */}

        {socialLinks.length > 0 && (

          <div>

            <h3
              style={{
                color:
                  footer.headingColor ||
                  "#ffffff",
              }}
            >
              Follow Us
            </h3>


            <div
              style={
                styles.socialLinks
              }
            >

              {socialLinks.map(
                (social, index) => (

                  <a
                    key={
                      social?._key ||
                      index
                    }
                    href={
                      social?.url ||
                      "#"
                    }
                    target="_blank"
                    rel="noreferrer"
                    style={{
                      color:
                        footer.iconColor ||
                        "#ffffff",
                    }}
                  >
                    {cleanText(
                      social?.platform ||
                      social?.label
                    )}
                  </a>

                )
              )}

            </div>

          </div>

        )}

      </div>


      {/* COPYRIGHT */}

      <div
        style={{
          ...styles.copyright,

          borderTop:
            footer.borderTop
              ? `1px solid ${
                  footer.borderColor ||
                  "rgba(255,255,255,0.15)"
                }`
              : "none",
        }}
      >
        {cleanText(
          footer.copyrightText
        )}
      </div>

    </footer>
  );
}


/* =========================================================
   STYLES
========================================================= */

const styles = {

  /* =======================================================
     PAGE
  ======================================================= */

  page: {
    minHeight: "100vh",

    background:
      "linear-gradient(135deg, #fff7fb 0%, #fdf9ff 50%, #f7f8ff 100%)",

    padding:
      "50px 30px",

    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",

    boxSizing:
      "border-box",
  },


  container: {
    maxWidth:
      "1000px",

    margin:
      "0 auto",
  },


  /* =======================================================
     HEADER
  ======================================================= */

  header: {
    display:
      "flex",

    alignItems:
      "center",

    gap:
      "20px",

    marginBottom:
      "35px",
  },


  icon: {
    width:
      "65px",

    height:
      "65px",

    borderRadius:
      "20px",

    background:
      "linear-gradient(135deg, #e88bb5, #b78bea)",

    display:
      "flex",

    alignItems:
      "center",

    justifyContent:
      "center",

    fontSize:
      "30px",

    boxShadow:
      "0 10px 30px rgba(200, 130, 190, 0.25)",
  },


  title: {
    margin:
      0,

    fontSize:
      "32px",

    fontWeight:
      "700",

    color:
      "#222",

    letterSpacing:
      "-0.5px",
  },


  subtitle: {
    margin:
      "7px 0 0",

    fontSize:
      "15px",

    color:
      "#777",

    lineHeight:
      "1.5",
  },


  /* =======================================================
     PROMPT CARD
  ======================================================= */

  card: {
    background:
      "#ffffff",

    borderRadius:
      "24px",

    padding:
      "30px",

    boxShadow:
      "0 15px 50px rgba(40, 30, 60, 0.08)",

    border:
      "1px solid rgba(0,0,0,0.05)",
  },


  label: {
    display:
      "block",

    fontSize:
      "17px",

    fontWeight:
      "600",

    color:
      "#333",

    marginBottom:
      "14px",
  },


  textarea: {
    width:
      "100%",

    minHeight:
      "180px",

    padding:
      "20px",

    borderRadius:
      "18px",

    border:
      "1px solid #e5e5e5",

    outline:
      "none",

    resize:
      "vertical",

    fontSize:
      "15px",

    lineHeight:
      "1.6",

    color:
      "#333",

    background:
      "#fcfcfc",

    boxSizing:
      "border-box",

    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },


  bottomRow: {
    display:
      "flex",

    justifyContent:
      "space-between",

    alignItems:
      "center",

    marginTop:
      "8px",
  },


  characterCount: {
    fontSize:
      "12px",

    color:
      "#999",
  },


  clearButton: {
    background:
      "transparent",

    border:
      "none",

    color:
      "#999",

    cursor:
      "pointer",

    fontSize:
      "13px",
  },


  error: {
    display:
      "flex",

    gap:
      "10px",

    alignItems:
      "center",

    marginTop:
      "18px",

    padding:
      "14px 16px",

    background:
      "#fff1f1",

    borderRadius:
      "12px",

    color:
      "#c0392b",

    fontSize:
      "14px",
  },


  generateButton: {
    width:
      "100%",

    marginTop:
      "22px",

    padding:
      "16px 24px",

    border:
      "none",

    borderRadius:
      "14px",

    background:
      "linear-gradient(135deg, #e88bb5, #b78bea)",

    color:
      "#ffffff",

    fontSize:
      "16px",

    fontWeight:
      "600",

    boxShadow:
      "0 10px 25px rgba(190, 120, 190, 0.25)",
  },


  spinner: {
    marginRight:
      "8px",
  },


  /* =======================================================
     EXAMPLES
  ======================================================= */

  examplesSection: {
    marginTop:
      "35px",
  },


  sectionTitle: {
    fontSize:
      "18px",

    fontWeight:
      "600",

    color:
      "#333",

    marginBottom:
      "15px",
  },


  examplesGrid: {
    display:
      "grid",

    gridTemplateColumns:
      "repeat(auto-fit, minmax(280px, 1fr))",

    gap:
      "14px",
  },


  exampleCard: {
    textAlign:
      "left",

    background:
      "#ffffff",

    border:
      "1px solid #eeeeee",

    borderRadius:
      "16px",

    padding:
      "18px",

    cursor:
      "pointer",

    display:
      "flex",

    gap:
      "14px",

    alignItems:
      "flex-start",

    transition:
      "all 0.2s ease",
  },


  exampleNumber: {
    minWidth:
      "30px",

    height:
      "30px",

    borderRadius:
      "10px",

    background:
      "#fff0f6",

    color:
      "#d76c9d",

    display:
      "flex",

    alignItems:
      "center",

    justifyContent:
      "center",

    fontSize:
      "13px",

    fontWeight:
      "700",
  },


  exampleText: {
    fontSize:
      "13px",

    color:
      "#666",

    lineHeight:
      "1.5",
  },


  /* =======================================================
     PREVIEW CARD
  ======================================================= */

  previewCard: {
    marginTop:
      "35px",

    background:
      "#ffffff",

    borderRadius:
      "24px",

    padding:
      "30px",

    boxShadow:
      "0 15px 50px rgba(40, 30, 60, 0.08)",

    border:
      "1px solid rgba(0,0,0,0.05)",
  },


  previewHeader: {
    display:
      "flex",

    justifyContent:
      "space-between",

    alignItems:
      "center",

    marginBottom:
      "25px",

    gap:
      "20px",
  },


  previewTitle: {
    margin:
      0,

    fontSize:
      "22px",

    color:
      "#222",
  },


  previewSubtitle: {
    margin:
      "6px 0 0",

    color:
      "#888",

    fontSize:
      "13px",
  },


  successBadge: {
    background:
      "#edf9f1",

    color:
      "#2e8b57",

    padding:
      "7px 12px",

    borderRadius:
      "20px",

    fontSize:
      "12px",

    fontWeight:
      "600",

    whiteSpace:
      "nowrap",
  },


  preview: {
    borderRadius:
      "18px",

    overflow:
      "hidden",

    border:
      "1px solid #eeeeee",

    minHeight:
      "600px",

    width:
      "100%",
  },


  /* =======================================================
     CMS NAVBAR
  ======================================================= */

  cmsNavbar: {
    minHeight:
      "70px",

    padding:
      "0 35px",

    display:
      "flex",

    justifyContent:
      "space-between",

    alignItems:
      "center",

    gap:
      "20px",

    boxSizing:
      "border-box",
  },


  cmsSiteTitle: {
    fontSize:
      "20px",

    fontWeight:
      "700",

    whiteSpace:
      "nowrap",
  },


  cmsNavLinks: {
    display:
      "flex",

    alignItems:
      "center",

    gap:
      "22px",

    flexWrap:
      "wrap",

    justifyContent:
      "flex-end",
  },


  cmsNavLink: {
    textDecoration:
      "none",

    fontSize:
      "14px",

    fontWeight:
      "500",
  },


  /* =======================================================
     HERO
  ======================================================= */

  cmsHero: {
    minHeight:
      "480px",

    padding:
      "70px 40px",

    position:
      "relative",

    display:
      "flex",

    alignItems:
      "center",

    justifyContent:
      "center",

    boxSizing:
      "border-box",

    backgroundRepeat:
      "no-repeat",
  },


  heroOverlay: {
    position:
      "absolute",

    inset:
      0,

    zIndex:
      1,
  },


  heroContent: {
    maxWidth:
      "800px",

    width:
      "100%",

    display:
      "flex",

    flexDirection:
      "column",

    alignItems:
      "center",

    justifyContent:
      "center",
  },


  heroImage: {
    marginBottom:
      "25px",

    objectFit:
      "cover",

    boxShadow:
      "0 15px 40px rgba(0,0,0,0.18)",
  },


  cmsHeroHeading: {
    margin:
      "0 0 12px",

    fontSize:
      "48px",

    lineHeight:
      "1.1",

    fontWeight:
      "800",
  },


  cmsHeroRole: {
    margin:
      "0 0 15px",

    fontSize:
      "24px",

    fontWeight:
      "500",

    opacity:
      0.9,
  },


  cmsHeroDescription: {
    maxWidth:
      "650px",

    margin:
      "0 auto",

    fontSize:
      "17px",

    lineHeight:
      "1.7",

    opacity:
      0.9,
  },


  heroButtons: {
    display:
      "flex",

    gap:
      "14px",

    flexWrap:
      "wrap",

    justifyContent:
      "center",

    marginTop:
      "30px",
  },


  cmsButton: {
    display:
      "inline-flex",

    alignItems:
      "center",

    justifyContent:
      "center",

    padding:
      "13px 24px",

    borderRadius:
      "10px",

    textDecoration:
      "none",

    fontWeight:
      "600",

    fontSize:
      "14px",

    cursor:
      "pointer",
  },


  /* =======================================================
     SECTIONS
  ======================================================= */

  cmsSection: {
    padding:
      "70px 40px",

    boxSizing:
      "border-box",
  },


  sectionInner: {
    maxWidth:
      "1000px",

    margin:
      "0 auto",
  },


  sectionText: {
    maxWidth:
      "900px",

    margin:
      "0 auto",
  },


  cmsSectionHeading: {
    margin:
      "0 0 14px",

    fontSize:
      "34px",

    fontWeight:
      "750",

    lineHeight:
      "1.2",
  },


  cmsSectionDescription: {
    maxWidth:
      "750px",

    fontSize:
      "16px",

    lineHeight:
      "1.7",

    color:
      "#555",

    marginBottom:
      "30px",
  },


  /* =======================================================
     ABOUT
  ======================================================= */

  aboutImage: {
    width:
      "150px",

    height:
      "150px",

    objectFit:
      "cover",

    marginBottom:
      "25px",

    boxShadow:
      "0 10px 30px rgba(0,0,0,0.12)",
  },


  featureGrid: {
    display:
      "grid",

    gridTemplateColumns:
      "repeat(auto-fit, minmax(180px, 1fr))",

    gap:
      "18px",

    marginTop:
      "25px",
  },


  featureCard: {
    padding:
      "22px",

    border:
      "1px solid rgba(0,0,0,0.06)",
  },


  /* =======================================================
     SERVICES
  ======================================================= */

  serviceGrid: {
    display:
      "grid",

    gap:
      "20px",

    marginTop:
      "30px",
  },


  serviceCard: {
    padding:
      "25px",

    border:
      "1px solid rgba(0,0,0,0.06)",

    minHeight:
      "180px",

    boxSizing:
      "border-box",
  },


  serviceImage: {
    width:
      "100%",

    height:
      "150px",

    objectFit:
      "cover",

    borderRadius:
      "12px",

    marginBottom:
      "18px",
  },


  smallButton: {
    display:
      "inline-block",

    marginTop:
      "14px",

    padding:
      "10px 17px",

    borderRadius:
      "8px",

    color:
      "#ffffff",

    background:
      "#111827",

    textDecoration:
      "none",

    fontSize:
      "13px",

    fontWeight:
      "600",
  },


  /* =======================================================
     PORTFOLIO
  ======================================================= */

  projectGrid: {
    display:
      "grid",

    gap:
      "20px",

    marginTop:
      "30px",
  },


  projectCard: {
    padding:
      "20px",

    borderRadius:
      "16px",

    background:
      "#ffffff",

    border:
      "1px solid #eeeeee",

    boxShadow:
      "0 5px 20px rgba(0,0,0,0.05)",

    boxSizing:
      "border-box",
  },


  projectImage: {
    width:
      "100%",

    height:
      "180px",

    objectFit:
      "cover",

    borderRadius:
      "12px",

    marginBottom:
      "18px",
  },


  projectBadge: {
    display:
      "inline-block",

    marginTop:
      "8px",

    padding:
      "5px 10px",

    borderRadius:
      "20px",

    background:
      "#eef2ff",

    color:
      "#4f46e5",

    fontSize:
      "11px",

    fontWeight:
      "600",
  },


  projectMeta: {
    marginTop:
      "7px",

    fontSize:
      "12px",

    color:
      "#777",
  },


  /* =======================================================
     CONTACT
  ======================================================= */

  contactGrid: {
    display:
      "grid",

    gridTemplateColumns:
      "repeat(auto-fit, minmax(220px, 1fr))",

    gap:
      "18px",

    marginTop:
      "30px",
  },


  contactItem: {
    padding:
      "22px",

    borderRadius:
      "14px",

    border:
      "1px solid rgba(0,0,0,0.06)",

    display:
      "flex",

    flexDirection:
      "column",

    gap:
      "8px",
  },


  /* =======================================================
     FOOTER
  ======================================================= */

  cmsFooter: {
    padding:
      "50px 40px 25px",

    boxSizing:
      "border-box",
  },


  footerGrid: {
    maxWidth:
      "1000px",

    margin:
      "0 auto",

    display:
      "grid",

    gridTemplateColumns:
      "repeat(auto-fit, minmax(180px, 1fr))",

    gap:
      "30px",
  },


  footerLinks: {
    display:
      "flex",

    flexDirection:
      "column",

    gap:
      "9px",
  },


  footerContact: {
    marginBottom:
      "10px",

    fontSize:
      "13px",
  },


  socialLinks: {
    display:
      "flex",

    flexWrap:
      "wrap",

    gap:
      "12px",
  },


  copyright: {
    maxWidth:
      "1000px",

    margin:
      "35px auto 0",

    paddingTop:
      "20px",

    fontSize:
      "12px",

    opacity:
      0.75,
  },
};